feat: add a news article about the Baby Bliss Bot project
fluid-project/floeproject.org pull request #303
Opened 2023-06-28 17:19 UTC by cindyli

@agamba, could you review this news article. Pinging you here as your github id is not showing up in the reviewers list.

2023-06-28 19:52 UTC, klown requested changes

2023-06-28 19:52 UTC, klown commented on src/collections/news/2023-04-12-BBB-Intro.md
> +project embarks on a community-led investigation to explore the possibilities and challenges of
Suggest replacement for "embarks on" in "The Baby Bliss Bot (BBB) project embarks on a community-led investigation ..."

Instead:  "The Baby Bliss Bot (BBB) project is a community-led investigation ..."

2023-06-28 20:06 UTC, cindyli commented
@klown thanks for the comment. It has been addressed and ready for another look.

2023-06-28 21:02 UTC, klown approved these changes
Look good to me @cindyli.

2023-06-28 22:11 UTC, merged

2023-06-29 21:36 UTC, agamba commented on src/collections/news/2023-04-12-BBB-Intro.md
> +method for teaching communication to children with physical disabilities who are non-speaking.
I suggest rephrasing 
"has gained popularity as a method for teaching communication to children with physical disabilities who are non-speaking."
by
"has gained popularity as a method for assisting language development and communication skills to children with physical disabilities who are non-speaking."

2023-06-29 21:39 UTC, agamba commented on src/collections/news/2023-04-12-BBB-Intro.md
> +tremendous opportunity to enhance societal engagement for nonvocal citizens but also comes with many
Not sure if we want to make the statement refer to "nonvocal citizens" or more broadly to "nonvocal individuals"

2023-06-29 22:01 UTC, cindyli commented
Thanks for comments, @agamba. I've addressed them all and pushed to the main branch.